name: Update GameThreads.json

on:
  repository_dispatch:
    types: [ThreadUpdate]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GameBot"
          git config user.email "gamebot@example.com"

      - name: Update GameThreads.json
        run: |
          echo '${{ github.event.client_payload.data }}' > GameThreads.json

      - name: Commit and push
        run: |
          git add GameThreads.json
          git commit -m "Update GameThreads.json (auto-save)"
          git push
